### ISSUE TITLE
[R] knit problem

### ISSUE THREAD

**Issue by AndersFugl** [bss-osca/tfa#11]
Hi, 
I can't knit this document. I have tried to uninstall all the packages with 'remove.packages' and installed them again, but that didn't work. I hope you guys have some answers for me.

```{r, cashe=FALSE}
library(tidyverse)
library(skimr)
library(fitdistrplus)
```

```{r}
gapminder %>%
  select(year, lifeExp)

gapminder %>%
  filter((gdpPercap > 40000 & continent == "Europe") | (gdpPercap < 500 & continent == "Africa")) %>%
  select(continent, country, gdpPercap) %>%
  arrange(desc(gdpPercap)) 
```

This is the error from the Render:
![image](https://user-images.githubusercontent.com/94283118/145367674-4b3e1597-429e-4e7c-8f3c-47b867946826.png)

This is the error when I try to run the chunk:
![image](https://user-images.githubusercontent.com/94283118/145367964-4b65addc-85c3-4562-84ab-7b377e2397e0.png)

@relund @JesperBangMikkelsen @jubaau

**Comment by JesperBangMikkelsen** [comment]
Hi Anders,

Have you included the package `gapminder`? 
It is required for using the dataset in your code

Best regards,
Jesper

**Comment by AndersFugl** [comment]
Hi Jesper,

yes, I have included the package. I do not have any problems running 'gapminder' alone.

![image](https://user-images.githubusercontent.com/94283118/145381233-b3b29066-5d8e-4841-9721-e1ea8e0541d2.png)

/ Anders

**Comment by jubaau** [comment]
Hi Anders,

try

gapminder %>% dplyr::select(year, lifeExp)

to explicitly run the select function from the dplyr package. If you load the packages one after another you should get a message like "Loading required package: MASS

Attaching package: ‘MASS’

The following object is masked from ‘package:dplyr’:

    select"

at some point. This means that there are functions in several packages with the same name that do different things. You could change the sequence in which you load the packages. But try the above, then it should work in any case.

Does it work?

Regards,
Julian

**Comment by AndersFugl** [comment]
Hi Julian,
I have change all the 'select' to 'dplyr::select' and it is working now. 
Thanks for the help to the both of you!

Best regards,
Anders
