### ISSUE TITLE
[R] Packages for the exam

### ISSUE THREAD

**Issue by 201804159** [bss-osca/tfa#13]
Hi Lars

I think you have mentioned during the last lecture that you will inform us about which packages we have to have installed for the R part of the exam. I do not seem to be able to find this information. Could you please be so kind to guide me to the place I can read about that?

Thank you for your help.

BR Galina

**Comment by relund** [comment]
I would be good to install packages `tidyverse, fitdistrplus, skimr` and `conflicted`

Best Lars
