### ISSUE TITLE
[R] Loading packages in R

### ISSUE THREAD

**Issue by AU531232** [bss-osca/tfa#5]
Hello

I have had some problems loading packages in R. Especially the package called 'TFA'. This should be used in the exercises for last time, but also the first assignment in module 15. The following hint: 

remotes::install_github("bss-osca/tfa/tfa-package", upgrade = FALSE)  # run to upgrade

This does not help me loading it. Can you help me, or tell me what to do different? 

Kind regards.

**Comment by jubaau** [comment]
Hi,

you probably got a hint in the R console that the package remotes is not installed. Please check for that. If this is the case, install the package by running the command

install.packages("remotes")

in the R console.

Then run the command that you mentioned again to install the tfa library.

Regards,
Julian

**Comment by AU531232** [comment]
I think it is working now. Thank you so much! :-)

**Comment by AU531232** [comment]
The package is now working. But when I use the TFA template and try to knit the document this message appears. Do you know what the problem is? 
![Skærmbillede 2021-11-11 112224](https://user-images.githubusercontent.com/94107679/141281612-c737d466-5d6c-4ada-ae60-fbfee3f12ddc.png)

**Comment by jubaau** [comment]
you also have to install "devtools" by install.packages("devtools").
There should also be another package that you have to install

**Comment by AU531232** [comment]
It is working now, thank you.
