### ISSUE TITLE
Assignment 2 (R Part)- Reexam 

### ISSUE THREAD

**Issue by raquelsimoes** [bss-osca/tfa#6]
Hi

About the Assignment 2 in the R part of the reexam:

I have an issue in reading the "titanic.csv" file by using my R Desktop version because every time I insert the code there, it says the document has not been found in the current working directory as shown in the screenshot below.

I've tried to download the file from this link: https://github.com/bss-osca/tfa/tree/master/exams/2021-02_reexam/solution/r , but it only allows me to download the link in HTML format. Therefore, when I try to insert the code again, it reads something completely different from the table shown in the link.

How can I read the file accordingly, by using my R desktop version?

Thank you in advance!

Regards,

Ana Simões

![Screen Shot 2021-11-25 at 14 04 11](https://user-images.githubusercontent.com/92940465/143446974-71c7bf8a-dedf-4c22-b3d6-53a18b773fd8.png)

**Comment by JesperBangMikkelsen** [comment]
Hi Ana,

I recommend that you just download the entire GitHub folder as a zip file and extract it on your computer. Then you will have all files available locally.

You can do this by going to the front page of the TFA GitHub folder [here](https://github.com/bss-osca/tfa), press "Code" and then "Download Zip". Then you will then get all the files from the GitHub folder including "titanic.csv"
![image](https://user-images.githubusercontent.com/89013617/143542407-e013f7c2-9de6-4131-aa95-8a3f0116fac0.png)

Regards,
Jesper

**Comment by JesperBangMikkelsen** [comment]
Hi Ana, 

Have you placed the file directly in your working directory and not in a folder in your working directory? If you want to load it with read_csv("titanic.csv") then the file needs to be placed directly in your working directory and not in any subfolders in your working directory.  Alternatively, if the file is placed in a subfolder in your working directory (let's say it's placed in a folder called TFA in your working directory) then you need to put that folder in the path like read_csv("TFA/titanic.csv") :)

Regards,
Jesper
