### ISSUE TITLE
R Project Report

### ISSUE THREAD

**Issue by raquelsimoes** [bss-osca/tfa#7]
Hi,

I have a question regarding the project because, in the first exercise, the purpose is to read first the excel file and then afterward allocate the data from the excel file to the JSON file according to the specific parameters or what is the main purpose of the first exercise, because I do not know if we should start by reading the excel file and then afterward allocate the data accordingly or if there is another way to do it. Could you just give some tips about how we should start to approach this, please?

Thank you in advance!

Regards,

Ana

**Comment by jubaau** [comment]
Hi Ana,

yes, that is how it should be done. First read the data to R, e.g., in a list and then write them to the .json file.

Regards
Julian
